name = "kiss"
version = "0.1.0"
license = "license"
author = "Ivan Pribec"
maintainer = "ivan.pribec@gmail.com"
copyright = "Copyright 2025, Ivan Pribec"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = ["blas", "lapack"]

[install]
library = false


[dev-dependencies]
fortuno = { git = "https://github.com/fortuno-repos/fortuno-fpm-serial.git" }
